version: "2"

services:

########################################################################################################################
###   Alfresco Content Services (ACS)
########################################################################################################################

   alfresco:
        image: alfresco/alfresco-content-repository:6.2.1
        environment:
            JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/acs
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=127.0.0.1
                -Dshare.port=8080
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dmetadata-keystore.password=mp6yc0UD9e
                -Dmetadata-keystore.aliases=metadata
                -Dmetadata-keystore.metadata.password=mp6yc0UD9e
                -Dmetadata-keystore.metadata.algorithm=AES
                -Dtransform.service.enabled=true
                -Dtransform.service.url=http://transform-router:8095
                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
                -Dalfresco-pdf-renderer.url=http://transform-core-aio:8090/
                -Djodconverter.url=http://transform-core-aio:8090/
                -Dimg.url=http://transform-core-aio:8090/
                -Dtika.url=http://transform-core-aio:8090/
                -Dtransform.misc.url=http://transform-core-aio:8090/
                -Dsfs.url=http://shared-file-store:8099/
                -Dcsrf.filter.enabled=false
                -Ddsync.service.uris=http://localhost:9090/alfresco
                -Xms1500m
                -Xmx1500m
                "
        volumes:
          - ./data/acs:/usr/local/tomcat/alf_data/
#          - ./acs/alfresco-global.properties:/usr/local/tomcat/shared/classes/alfresco-global.properties
#          - ./acs/log4j.properties:/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/log4j.properties
          - ./acs/license:/usr/local/tomcat/shared/classes/alfresco/extension/license
        depends_on:
          - solr6
        ports:
          - 8082:8080 # Need a separate port mapping for this so we can talk directly from inside APS

   transform-router:
        image: quay.io/alfresco/alfresco-transform-router:1.2.0
        environment:
          JAVA_OPTS: " -Xms256m -Xmx512m"
          ACTIVEMQ_URL: "nio://activemq:61616"
          CORE_AIO_URL : "http://transform-core-aio:8090"
          FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8095:8095
        links:
          - activemq

   transform-core-aio:
        image: alfresco/alfresco-transform-core-aio:2.2.1
        environment:
            JAVA_OPTS: " -Xms256m -Xmx1536m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8090:8090
        links:
        - activemq


   shared-file-store:
        image: alfresco/alfresco-shared-file-store:0.7.0
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            scheduler.content.age.millis: 86400000
            scheduler.cleanup.interval: 86400000
        ports:
            - 8099:8099
        volumes:
            - shared-file-store-volume:/tmp/Alfresco/sfs

   share:
        image: alfresco/alfresco-share:6.2.1
        environment:
            REPO_HOST: "alfresco"
            REPO_PORT: "8080"
            JAVA_OPTS: "
                -Xms500m
                -Xmx500m
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Dalfresco.context=alfresco
                -Dalfresco.protocol=http
                "

   solr6:
        image: alfresco/alfresco-search-services:1.4.2
        environment:
            #Solr needs to know how to register itself with Alfresco
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=8080
            #Alfresco needs to know how to call solr
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=8983
            #Create the default alfresco and archive cores
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
            #HTTP by default
            - ALFRESCO_SECURE_COMMS=none
            - "SOLR_JAVA_MEM=-Xms2g -Xmx2g"
        ports:
            - 8083:8983 #Browser port

   activemq:
        image: alfresco/alfresco-activemq:5.15.8
        ports:
            - 8161:8161 # Web Console
            - 5672:5672 # AMQP
            - 61616:61616 # OpenWire
            - 61613:61613 # STOMP

   digital-workspace:
        image: quay.io/alfresco/alfresco-digital-workspace:1.5.0
        mem_limit: 128m
        environment:
            BASE_PATH: ./

   proxy:
        image: alfresco/alfresco-acs-nginx:3.0.1
        depends_on:
            - alfresco
            - digital-workspace
        ports:
            - 8080:8080
        links:
            - digital-workspace
            - alfresco
            - share

   sync-service:
        image: quay.io/alfresco/service-sync:3.3.2
        environment:
            JAVA_OPTS : "
            -Dsql.db.driver=org.postgresql.Driver
            -Dsql.db.url=jdbc:postgresql://postgres:5432/alfresco
            -Dsql.db.username=alfresco
            -Dsql.db.password=alfresco
            -Dmessaging.broker.host=activemq
            -Drepo.hostname=alfresco
            -Drepo.port=8080
            -Ddw.server.applicationConnectors[0].type=http
            -Xms1000m -Xmx1000m
            "
        ports:
            - 9090:9090
            
########################################################################################################################
###   Alfresco Process Services (APS)
########################################################################################################################

   process:
        image: alfresco/process-services:1.11.0
        environment:
          CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
          ACTIVITI_DATASOURCE_USERNAME: alfresco
          ACTIVITI_DATASOURCE_PASSWORD: alfresco
          ACTIVITI_DATASOURCE_DRIVER: org.postgresql.Driver
          ACTIVITI_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
          ACTIVITI_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/aps?characterEncoding=UTF-8'
          ACTIVITI_CSRF_DISABLED: 'true'
          ACTIVITI_CORS_ENABLED: 'true'
          ACTIVITI_ES_SERVER_TYPE: client
          ACTIVITI_ES_DISCOVERY_HOSTS: elasticsearch:9300
          ACTIVITI_ES_CLUSTER_NAME: elasticsearch
        volumes:
          - ./aps/enterprise-license:/root/.activiti/enterprise-license/:ro
          - ./aps/transform.lic:/usr/share/tomcat/lib/transform.lic
          - ./aps/activiti-app.properties:/usr/share/tomcat/lib/activiti-app.properties
#          - ./aps/activiti-identity-service.properties:/usr/local/tomcat/lib/activiti-identity-service.properties
#          - ./aps/activiti-ldap.properties:/usr/local/tomcat/lib/activiti-ldap.properties
          - ./aps/log4j.properties:/usr/share/tomcat/webapps/activiti-app/WEB-INF/classes/log4j.properties
          - ./data/aps:/usr/local/data/
        ports:
          - 9080:8080 # Browser port
          - 5006:5005 # Remote Debug
        depends_on:
          - elasticsearch

   elasticsearch:
        image: elasticsearch:1.7.3

# Docker Volumes for ACS
volumes:
    shared-file-store-volume:
        driver_opts:
            type: tmpfs
            device: tmpfs

# Let all containers join the default docker network created by the docker-compose-identity/docker-compose.yml file
networks:
    default:
        external:
            name: docker-compose-identity_default
