version: "2"

services:
    postgres:
        image: postgres:11.4
        mem_limit: 512m
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
            - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d

    transform-router:
        mem_limit: 512m
        image: quay.io/alfresco/alfresco-transform-router:1.1.1
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            IMAGEMAGICK_URL: "http://imagemagick:8090"
            PDF_RENDERER_URL: "http://alfresco-pdf-renderer:8090"
            LIBREOFFICE_URL: "http://libreoffice:8090"
            TIKA_URL: "http://tika:8090"
            MISC_URL: "http://transform-misc:8090"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8095:8095

    alfresco-pdf-renderer:
        image: alfresco/alfresco-pdf-renderer:2.1.1
        mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8090:8090

    imagemagick:
        image: alfresco/alfresco-imagemagick:2.1.1
        mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8091:8090

    libreoffice:
        image: alfresco/alfresco-libreoffice:2.1.1
        mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8092:8090

    tika:
        image: alfresco/alfresco-tika:2.1.1
        mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8093:8090

    transform-misc:
        image: alfresco/alfresco-transform-misc:2.1.1
        mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8094:8090

    elasticsearch:
        image: elasticsearch:1.7.3

    process:
        image: alfresco/process-services:1.11.0
        environment:
          CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
          ACTIVITI_DATASOURCE_USERNAME: alfresco
          ACTIVITI_DATASOURCE_PASSWORD: alfresco
          ACTIVITI_DATASOURCE_DRIVER: org.postgresql.Driver
          ACTIVITI_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
          ACTIVITI_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/activiti?characterEncoding=UTF-8'
          ACTIVITI_CSRF_DISABLED: 'true'
          ACTIVITI_CORS_ENABLED: 'true'
          ACTIVITI_ES_SERVER_TYPE: client
          ACTIVITI_ES_DISCOVERY_HOSTS: elasticsearch:9300
          ACTIVITI_ES_CLUSTER_NAME: elasticsearch
        volumes:
          - ./aps/enterprise-license:/root/.activiti/enterprise-license/:ro
          - ./aps/transform.lic:/usr/share/tomcat/lib/transform.lic
          - ./aps/activiti-app.properties:/usr/share/tomcat/lib/activiti-app.properties
#          - ./aps/activiti-identity-service.properties:/usr/local/tomcat/lib/activiti-identity-service.properties
          - ./aps/log4j.properties:/usr/share/tomcat/webapps/activiti-app/WEB-INF/classes/log4j.properties
          - ./data/aps:/usr/local/data/
        ports:
          - 9080:8080 # Browser port
          - 5006:5005 # Remote Debug
        depends_on:
          - elasticsearch
          - postgres

    alfresco:
        image: alfresco/alfresco-content-repository:6.2.0.2
        mem_limit: 1700m
        environment:
            JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=127.0.0.1
                -Dshare.port=8080
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dtransform.service.enabled=true
                -Dtransform.service.url=http://transform-router:8095
                -Dsfs.url=http://shared-file-store:8099/
                -Dlocal.transform.service.enabled=true
                -DlocalTransform.pdfrenderer.url=http://alfresco-pdf-renderer:8090/
                -DlocalTransform.imagemagick.url=http://imagemagick:8090/
                -DlocalTransform.libreoffice.url=http://libreoffice:8090/
                -DlocalTransform.tika.url=http://tika:8090/
                -DlocalTransform.misc.url=http://transform-misc:8090/
                -Dlegacy.transform.service.enabled=true
                -Dalfresco-pdf-renderer.url=http://alfresco-pdf-renderer:8090/
                -Djodconverter.url=http://libreoffice:8090/
                -Dimg.url=http://imagemagick:8090/
                -Dtika.url=http://tika:8090/
                -Dtransform.misc.url=http://transform-misc:8090/
                -Dcsrf.filter.enabled=false
                -DtrialUid=id10288029
                -Dsync.mode=OFF
                -Xms1500m
                -Xmx1500m
                "
        volumes:
          - ./data/acs:/usr/local/tomcat/alf_data/
#          - ./acs/alfresco-global.properties:/usr/local/tomcat/shared/classes/alfresco-global.properties
#          - ./acs/log4j.properties:/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/log4j.properties
          - ./acs/license:/usr/local/tomcat/shared/classes/alfresco/extension/license
        depends_on:
          - solr6
          - postgres
        ports:
          - 8082:8080 # Need a separate port mapping for this so we can talk directly from inside APS

    solr6:
        image: alfresco/alfresco-search-services:1.4.0
        mem_limit: 2g
        environment:
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=8080
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=8983
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
            - ALFRESCO_SECURE_COMMS=none
            - "SOLR_JAVA_MEM=-Xms2g -Xmx2g"
        volumes:
            - ./data/solr/contentstore:/opt/alfresco-search-services/contentstore/
            - ./data/solr/data:/opt/alfresco-search-services/data/
        ports:
            - 8083:8983 #Browser port

    share:
        image: alfresco/alfresco-share:6.2.0
        mem_limit: 1g
        environment:
            REPO_HOST: "alfresco"
            REPO_PORT: "8080"
            JAVA_OPTS: " -Xms500m -Xmx500m -Dalfresco.host=localhost -Dalfresco.port=8080 -Dalfresco.context=alfresco -Dalfresco.protocol=http "

    shared-file-store:
        image: alfresco/alfresco-shared-file-store:0.5.3
        mem_limit: 512m
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            scheduler.content.age.millis: 86400000
            scheduler.cleanup.interval: 86400000
        ports:
            - 8099:8099
        volumes:
            - shared-file-store-volume:/tmp/Alfresco/sfs

    activemq:
        image: alfresco/alfresco-activemq:5.15.8
        mem_limit: 1g
        ports:
            - 8161:8161 # Web Console
            - 5672:5672 # AMQP
            - 61616:61616 # OpenWire
            - 61613:61613 # STOMP

    digital-workspace:
        image: quay.io/alfresco/alfresco-digital-workspace:1.4.0
        mem_limit: 128m
        environment:
            BASE_PATH: ./

    proxy:
        image: alfresco/alfresco-acs-nginx:3.0.1
        mem_limit: 128m
        depends_on:
            - alfresco
            - digital-workspace
            - share
        ports:
            - 8080:8080
        environment:
    #     ADW_URL: "http://digital-workspace"
    #     REPO_URL: "http://alfresco:8080"
    #     SHARE_URL: "http://share:8080"
            SYNCSERVICE_URL: ""

volumes:
    shared-file-store-volume:
        driver_opts:
            type: tmpfs
            device: tmpfs